name: pipeline_workflow
on: workflow_dispatch
jobs:
SumOfAAndB
runs-on: ubuntu-latest

steps:
name: Checkout repository
uses: actions/checkout@v3

name: setup node.js
uses: actions/setup-node@v3
with:
node-version: '16'

name: Install dependencies
run: [INSTALL_COMMAND]

name: run [description of task]
run: [command to run]
